//
//  Businesses.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class Businesses: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _businessId: String?
    var _businessAddress: String?
    var _businessCategory: String?
    var _businessDescription: String?
    var _businessEmail: String?
    var _businessImage: Data?
    var _businessLatitude: String?
    var _businessLongitude: String?
    var _businessName: String?
    var _businessPhone: String?
    var _businessWebsite: String?
    var _facebookUserID: String?
    var _fridayHours: String?
    var _mondayHours: String?
    var _saturdayHours: String?
    var _sundayHours: String?
    var _thursdayHours: String?
    var _tuesdayHours: String?
    var _wednesdayHours: String?
    var _activeBusiness: NSNumber?
    var _firstName: String?
    var _lastName: String?
    var _password: String?
    
    class func dynamoDBTableName() -> String {
        
        return "rnapps-mobilehub-22175013-Businesses"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_businessId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_businessId" : "BusinessId",
            "_businessAddress" : "BusinessAddress",
            "_businessCategory" : "BusinessCategory",
            "_businessDescription" : "BusinessDescription",
            "_businessEmail" : "BusinessEmail",
            "_businessImage" : "BusinessImage",
            "_businessLatitude" : "BusinessLatitude",
            "_businessLongitude" : "BusinessLongitude",
            "_businessName" : "BusinessName",
            "_businessPhone" : "BusinessPhone",
            "_businessWebsite" : "BusinessWebsite",
            "_facebookUserID" : "FacebookUserID",
            "_fridayHours" : "FridayHours",
            "_mondayHours" : "MondayHours",
            "_saturdayHours" : "SaturdayHours",
            "_sundayHours" : "SundayHours",
            "_thursdayHours" : "ThursdayHours",
            "_tuesdayHours" : "TuesdayHours",
            "_wednesdayHours" : "WednesdayHours",
            "_activeBusiness" : "activeBusiness",
            "_firstName" : "firstName",
            "_lastName" : "lastName",
            "_password" : "password",
        ]
    }
}
